In [1]:
import pandas as pd
import os

In [2]:
#########################
# Test
#########################
df = pd.read_csv("/Users/annika/annika/high-school/cs/tgca-downloads/SARC/8aa51bba-5e5c-4fe3-8ce0-dc2edd4b2154/jhu-usc.edu_SARC.HumanMethylation450.15.lvl-3.TCGA-DX-AB2L-01A-32D-A418-05.gdc_hg38.txt", sep = "\t")
df.sort_values(by='Composite Element REF', inplace=True)
df.head(5)

,Composite Element REF,Beta_value,Chromosome,Start,End,Gene_Symbol,Gene_Type,Transcript_ID,Position_to_TSS,CGI_Coordinate,Feature_Type
0,cg00000029,0.172221,chr16,53434200,53434201,RBL2;RBL2;RBL2,protein_coding;protein_coding;protein_coding,ENST00000262133.9;ENST00000544405.5;ENST000005...,-221;-1420;222,CGI:chr16:53434489-53435297,N_Shore
1,cg00000108,NaN,chr3,37417715,37417716,C3orf35;C3orf35;C3orf35;C3orf35;C3orf35;C3orf3...,lincRNA;lincRNA;lincRNA;lincRNA;lincRNA;lincRN...,ENST00000328376.8;ENST00000332506.6;ENST000004...,18552;18552;6505;31445;18143;447;18552;18552,CGI:chr3:37451927-37453047,.
2,cg00000109,NaN,chr3,172198247,172198248,FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B,protein_coding;protein_coding;protein_coding;p...,ENST00000336824.7;ENST00000415807.5;ENST000004...,157692;158618;151333;71272;158587;71273,CGI:chr3:172039703-172040934,.
3,cg00000165,0.127328,chr1,90729117,90729118,.,.,.,.,CGI:chr1:90724932-90727247,S_Shore
4,cg00000236,0.853673,chr8,42405776,42405777,VDAC3,protein_coding,ENST00000022615.7,13872,CGI:chr8:42410918-42411241,.

In [3]:
#########################
# Test
#########################
#Imputation by mean values to fill up missing values
df['Beta_value'].fillna(df['Beta_value'].mean(),inplace=True) 
df.head(5)

,Composite Element REF,Beta_value,Chromosome,Start,End,Gene_Symbol,Gene_Type,Transcript_ID,Position_to_TSS,CGI_Coordinate,Feature_Type
0,cg00000029,0.172221,chr16,53434200,53434201,RBL2;RBL2;RBL2,protein_coding;protein_coding;protein_coding,ENST00000262133.9;ENST00000544405.5;ENST000005...,-221;-1420;222,CGI:chr16:53434489-53435297,N_Shore
1,cg00000108,0.403907,chr3,37417715,37417716,C3orf35;C3orf35;C3orf35;C3orf35;C3orf35;C3orf3...,lincRNA;lincRNA;lincRNA;lincRNA;lincRNA;lincRN...,ENST00000328376.8;ENST00000332506.6;ENST000004...,18552;18552;6505;31445;18143;447;18552;18552,CGI:chr3:37451927-37453047,.
2,cg00000109,0.403907,chr3,172198247,172198248,FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B,protein_coding;protein_coding;protein_coding;p...,ENST00000336824.7;ENST00000415807.5;ENST000004...,157692;158618;151333;71272;158587;71273,CGI:chr3:172039703-172040934,.
3,cg00000165,0.127328,chr1,90729117,90729118,.,.,.,.,CGI:chr1:90724932-90727247,S_Shore
4,cg00000236,0.853673,chr8,42405776,42405777,VDAC3,protein_coding,ENST00000022615.7,13872,CGI:chr8:42410918-42411241,.

In [4]:
#########################
# Test
#########################
#transpose the rows and columns
df_transposed = df.T
df_transposed.head(5)

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
Beta_value,0.172221,0.403907,0.403907,0.127328,0.853673,0.442837,0.515537,0.257269,0.161422,0.00856218,...,0.0174542,0.96902,0.590762,0.97291,0.526648,0.935286,0.46105,0.543087,0.0472456,0.123651
Chromosome,chr16,chr3,chr3,chr1,chr8,chr14,chr16,chr8,chr1,chr15,...,chr6,chrX,chr21,chr1,chr5,chr6,chr3,chr15,chr2,chr3
Start,53434200,37417715,172198247,90729117,42405776,68874422,28878779,41310283,230425047,22838620,...,47163083,15867308,32625974,11429621,35000207,67522149,14617359,45707625,12008094,86613005
End,53434201,37417716,172198248,90729118,42405777,68874423,28878780,41310284,230425048,22838621,...,47163083,15867308,32625974,11429621,35000207,67522149,14617359,45707625,12008094,86613005

In [5]:
#########################
# Test
#########################
# Create a new variable called 'header' from the first row of the dataset
df_headers = df_transposed.iloc[0] 
df_headers.head(5)

0    cg00000029
1    cg00000108
2    cg00000109
3    cg00000165
4    cg00000236
Name: Composite Element REF, dtype: object

In [6]:
#########################
# Test
#########################
# Replace the dataframe with a new one which does not contain the first row
df_transposed = df_transposed[1:2]
df_transposed.head(5)

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
Beta_value,0.172221,0.403907,0.403907,0.127328,0.853673,0.442837,0.515537,0.257269,0.161422,0.00856218,...,0.0174542,0.96902,0.590762,0.97291,0.526648,0.935286,0.46105,0.543087,0.0472456,0.123651

In [7]:
#########################
# Test
#########################
# Rename the dataframe's column values with the header variable
df_transposed.rename(columns = df_headers, inplace=True)
df_transposed.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
Beta_value,0.172221,0.403907,0.403907,0.127328,0.853673,0.442837,0.515537,0.257269,0.161422,0.00856218,...,0.0174542,0.96902,0.590762,0.97291,0.526648,0.935286,0.46105,0.543087,0.0472456,0.123651

In [8]:
#########################
# Test
#########################
#Add a column with cancerType to the end of the data frame
df_transposed = df_transposed.assign(CancerType='SARC')
df_transposed.head(5) #scroll to the end to see the new column 'CancerType'

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.172221,0.403907,0.403907,0.127328,0.853673,0.442837,0.515537,0.257269,0.161422,0.00856218,...,0.96902,0.590762,0.97291,0.526648,0.935286,0.46105,0.543087,0.0472456,0.123651,SARC

In [9]:
#########################
# Test
#########################
#Read the next file
df2 = pd.read_csv("/Users/annika/annika/high-school/cs/tgca-downloads/SARC/559700c5-90c9-4a0e-8d6d-0a32b8660da7/jhu-usc.edu_SARC.HumanMethylation450.4.lvl-3.TCGA-PC-A5DP-01A-11D-A26S-05.gdc_hg38.txt", sep = "\t")
#Sort by the column which has the 'Composite Element REF'
df2.sort_values(by='Composite Element REF', inplace=True)
#Imputation by mean values to fill up missing values
df2['Beta_value'].fillna(df2['Beta_value'].mean(),inplace=True) 
#transpose the rows and columns
df2_transposed = df2.T
# Create a new variable called 'header' from the first row of the dataset
df2_headers = df2_transposed.iloc[0] 
# Replace the dataframe with a new one which does not contain the first row
df2_transposed = df2_transposed[1:2]
# Rename the dataframe's column values with the header variable
df2_transposed.rename(columns = df2_headers, inplace=True)
df2_transposed = df2_transposed.assign(CancerType='SARC')
df2_transposed.head()

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.198405,0.49723,0.49723,0.116141,0.925372,0.63108,0.899287,0.698576,0.576686,0.0112689,...,0.391209,0.120759,0.588087,0.96889,0.0639094,0.0241095,0.043873,0.0388983,0.954467,SARC

In [10]:
#########################
# Test
#########################
#concat the dataframes from the 2 files
dflist2 = [df_transposed]
dflist2.append(df2_transposed)
dfFinal2 = pd.concat(dflist2)
dfFinal2.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.172221,0.403907,0.403907,0.127328,0.853673,0.442837,0.515537,0.257269,0.161422,0.00856218,...,0.96902,0.590762,0.97291,0.526648,0.935286,0.46105,0.543087,0.0472456,0.123651,SARC
Beta_value,0.198405,0.49723,0.49723,0.116141,0.925372,0.63108,0.899287,0.698576,0.576686,0.0112689,...,0.391209,0.120759,0.588087,0.96889,0.0639094,0.0241095,0.043873,0.0388983,0.954467,SARC

In [11]:
#########################
# Test
#########################
# Save to csv file
filename = "SARC_betaValuesTesting2.csv"
dfFinal2.to_csv(filename,  index = False) # Do not save the index

In [14]:
#########################
# Test
#########################
#read from csv file in chunks
#filename = "LUAD_betaValuesTesting2.csv"
dfFrameList = []
for chunkTemp in pd.read_csv(filename, chunksize=1):
    dfFrameList.append(chunkTemp)
dataFrame = pd.concat(dfFrameList)        
dataFrame.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
0,0.481716,0.400710,0.400710,0.635898,0.915510,0.749313,0.793684,0.675040,0.619806,0.01095,...,0.013962,0.032053,0.017721,0.962484,0.952218,0.530360,0.047327,0.948374,0.961511,SKCM
1,0.651825,0.471031,0.471031,0.530507,0.921265,0.742232,0.721557,0.609868,0.710180,0.01517,...,0.367136,0.936100,0.013387,0.972289,0.315858,0.339031,0.971593,0.028026,0.867921,SKCM

In [1]:
#########################
# Program to preprocess all raw files for a cancer type
#########################
import pandas as pd
import os
import glob # Use glob to read files with wildcards

# Location for LUAD files
#For all files use this path
path = "/Users/annika/annika/high-school/cs/tgca-downloads/SARC/*/*n450*.*txt"

# Get the list of files
dirList = glob.glob(path)
# Initialize a list
dflist = []
for d in dirList:
    # Read the next file
    df3 = pd.read_csv(d, sep = "\t")
    # Sort by the column which has the 'Composite Element REF' so that 
    # the methalyation sites are sorted
    df3.sort_values(by='Composite Element REF', inplace=True)
    # Imputation by mean values to fill up missing values
    df3['Beta_value'].fillna(df3['Beta_value'].mean(),inplace=True) 
    # Transpose the rows and columns, so that all beta values are in a row
    df3_transposed = df3.T
    # Create a new variable called 'header' from the first row of the dataset which are
    # the values of 'Composite Element REF' e.g. cg00000029
    df3_headers = df3_transposed.iloc[0] 
    # Replace the dataframe with a new one which only contains the beta values
    df3_transposed = df3_transposed[1:2]
    # Rename the dataframe's column names with the header variable i.e. 
    # 'Composite Element REF' e.g. cg00000029
    df3_transposed.rename(columns = df3_headers, inplace=True)
    # Create a new column with the column name as 'CancerType' and value as 'LUAD'
    df3_transposed = df3_transposed.assign(CancerType='SARC')
    # concat the dataframes into a list
    dflist.append(df3_transposed)
# Convert the list to a dataframe    
dfFinal = pd.concat(dflist)
# Save the dataframe to csv file, do not save the index
dfFinal.to_csv("../../data/SARC/SARC_betaValuesOnly.csv", index = False) 
# Now the raw files can be deleted and only the csv files can be retained.

In [3]:
#dfFinal.to_csv("../../data/LUAD/LUAD_betaValuesOnly.csv", index = False) 
# Now the raw files can be deleted and only the csv files can be retained.

In [2]:
#########################
# Test
#########################
dfFinal.head(10)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.279142,0.428718,0.428718,0.829602,0.905728,0.663628,0.454632,0.349314,0.158887,0.0100885,...,0.974011,0.0619397,0.0166123,0.0307452,0.0449863,0.111427,0.475627,0.866996,0.938786,SARC
Beta_value,0.665216,0.461976,0.461976,0.165748,0.879694,0.699458,0.45532,0.454198,0.696979,0.0105854,...,0.032485,0.0525311,0.0137869,0.53215,0.0601693,0.199792,0.968522,0.519716,0.905133,SARC
Beta_value,0.407096,0.434562,0.434562,0.391648,0.901484,0.522674,0.492174,0.795632,0.136802,0.0265327,...,0.975052,0.389651,0.0160558,0.61781,0.617645,0.0236546,0.038261,0.925465,0.0943746,SARC
Beta_value,0.688334,0.456424,0.456424,0.170305,0.896771,0.642769,0.862639,0.38969,0.321772,0.014083,...,0.966792,0.0619443,0.0180894,0.49108,0.902802,0.509058,0.510416,0.505851,0.848447,SARC
Beta_value,0.093236,0.428315,0.428315,0.104714,0.768719,0.652771,0.871307,0.484505,0.124237,0.0158143,...,0.0133951,0.0457297,0.534396,0.958279,0.033788,0.484766,0.976553,0.580957,0.935753,SARC
Beta_value,0.128654,0.413029,0.413029,0.655383,0.871191,0.642283,0.267068,0.728034,0.144338,0.0156801,...,0.967542,0.923012,0.0139111,0.588408,0.0588999,0.964325,0.963953,0.937747,0.81478,SARC
Beta_value,0.138747,0.421981,0.421981,0.17835,0.920344,0.194785,0.542998,0.42146,0.203175,0.01325,...,0.958635,0.0471423,0.429708,0.955167,0.948842,0.978944,0.0745672,0.935746,0.938123,SARC
Beta_value,0.617342,0.474493,0.474493,0.730595,0.908277,0.717265,0.624391,0.563129,0.271096,0.0145382,...,0.373787,0.504456,0.495712,0.974264,0.0539343,0.970639,0.332063,0.39577,0.66198,SARC
Beta_value,0.265462,0.4155,0.4155,0.181761,0.883781,0.576561,0.442608,0.216644,0.10762,0.0131813,...,0.959091,0.459368,0.554199,0.965285,0.0559856,0.0314608,0.0344146,0.0407358,0.624186,SARC
Beta_value,0.336982,0.426447,0.426447,0.40034,0.872044,0.44183,0.518322,0.428352,0.211588,0.017173,...,0.0163764,0.327576,0.246646,0.967185,0.0433227,0.788231,0.485929,0.0499852,0.971199,SARC

In [3]:
dfFinal.shape

(201, 485578)