In [1]:
import pandas as pd
import os
#import fnmatch

In [2]:
#########################
# Test
#########################
df = pd.read_csv("/Users/annika/annika/high-school/cs/tgca-downloads/LGG/f5735fba-df9d-4320-81d5-f5fb9cb82477/jhu-usc.edu_LGG.HumanMethylation450.14.lvl-3.TCGA-TQ-A7RS-01A-12D-A33U-05.gdc_hg38.txt", sep = "\t")
df.sort_values(by='Composite Element REF', inplace=True)
#df.dtypes; #get the types
#type(df); #find the type of the variable
df.head(5)

,Composite Element REF,Beta_value,Chromosome,Start,End,Gene_Symbol,Gene_Type,Transcript_ID,Position_to_TSS,CGI_Coordinate,Feature_Type
0,cg00000029,0.895405,chr16,53434200,53434201,RBL2;RBL2;RBL2,protein_coding;protein_coding;protein_coding,ENST00000262133.9;ENST00000544405.5;ENST000005...,-221;-1420;222,CGI:chr16:53434489-53435297,N_Shore
1,cg00000108,NaN,chr3,37417715,37417716,C3orf35;C3orf35;C3orf35;C3orf35;C3orf35;C3orf3...,lincRNA;lincRNA;lincRNA;lincRNA;lincRNA;lincRN...,ENST00000328376.8;ENST00000332506.6;ENST000004...,18552;18552;6505;31445;18143;447;18552;18552,CGI:chr3:37451927-37453047,.
2,cg00000109,NaN,chr3,172198247,172198248,FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B,protein_coding;protein_coding;protein_coding;p...,ENST00000336824.7;ENST00000415807.5;ENST000004...,157692;158618;151333;71272;158587;71273,CGI:chr3:172039703-172040934,.
3,cg00000165,0.295116,chr1,90729117,90729118,.,.,.,.,CGI:chr1:90724932-90727247,S_Shore
4,cg00000236,0.864376,chr8,42405776,42405777,VDAC3,protein_coding,ENST00000022615.7,13872,CGI:chr8:42410918-42411241,.

In [3]:
#########################
# Test
#########################
#Imputation by mean values to fill up missing values
df['Beta_value'].fillna(df['Beta_value'].mean(),inplace=True) 
df.head(5)

,Composite Element REF,Beta_value,Chromosome,Start,End,Gene_Symbol,Gene_Type,Transcript_ID,Position_to_TSS,CGI_Coordinate,Feature_Type
0,cg00000029,0.895405,chr16,53434200,53434201,RBL2;RBL2;RBL2,protein_coding;protein_coding;protein_coding,ENST00000262133.9;ENST00000544405.5;ENST000005...,-221;-1420;222,CGI:chr16:53434489-53435297,N_Shore
1,cg00000108,0.531678,chr3,37417715,37417716,C3orf35;C3orf35;C3orf35;C3orf35;C3orf35;C3orf3...,lincRNA;lincRNA;lincRNA;lincRNA;lincRNA;lincRN...,ENST00000328376.8;ENST00000332506.6;ENST000004...,18552;18552;6505;31445;18143;447;18552;18552,CGI:chr3:37451927-37453047,.
2,cg00000109,0.531678,chr3,172198247,172198248,FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B,protein_coding;protein_coding;protein_coding;p...,ENST00000336824.7;ENST00000415807.5;ENST000004...,157692;158618;151333;71272;158587;71273,CGI:chr3:172039703-172040934,.
3,cg00000165,0.295116,chr1,90729117,90729118,.,.,.,.,CGI:chr1:90724932-90727247,S_Shore
4,cg00000236,0.864376,chr8,42405776,42405777,VDAC3,protein_coding,ENST00000022615.7,13872,CGI:chr8:42410918-42411241,.

In [4]:
#########################
# Test
#########################
#transpose the rows and columns
df_transposed = df.T
df_transposed.head(5)

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
Beta_value,0.895405,0.531678,0.531678,0.295116,0.864376,0.769955,0.889353,0.861963,0.855146,0.0127179,...,0.966964,0.353992,0.436706,0.932253,0.0219264,0.926977,0.564787,0.54919,0.919879,0.907564
Chromosome,chr16,chr3,chr3,chr1,chr8,chr14,chr16,chr8,chr1,chr15,...,chr6,chrX,chr21,chr1,chr5,chr6,chr3,chr15,chr2,chr3
Start,53434200,37417715,172198247,90729117,42405776,68874422,28878779,41310283,230425047,22838620,...,47163083,15867308,32625974,11429621,35000207,67522149,14617359,45707625,12008094,86613005
End,53434201,37417716,172198248,90729118,42405777,68874423,28878780,41310284,230425048,22838621,...,47163083,15867308,32625974,11429621,35000207,67522149,14617359,45707625,12008094,86613005

In [5]:
#########################
# Test
#########################
# Create a new variable called 'header' from the first row of the dataset
df_headers = df_transposed.iloc[0] 
#type(df_headers)
df_headers.head(5)

0    cg00000029
1    cg00000108
2    cg00000109
3    cg00000165
4    cg00000236
Name: Composite Element REF, dtype: object

In [6]:
#########################
# Test
#########################
# Replace the dataframe with a new one which does not contain the first row
df_transposed = df_transposed[1:2]
df_transposed.head(5)

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
Beta_value,0.895405,0.531678,0.531678,0.295116,0.864376,0.769955,0.889353,0.861963,0.855146,0.0127179,...,0.966964,0.353992,0.436706,0.932253,0.0219264,0.926977,0.564787,0.54919,0.919879,0.907564

In [7]:
#########################
# Test
#########################
# Rename the dataframe's column values with the header variable
df_transposed.rename(columns = df_headers, inplace=True)
df_transposed.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
Beta_value,0.895405,0.531678,0.531678,0.295116,0.864376,0.769955,0.889353,0.861963,0.855146,0.0127179,...,0.966964,0.353992,0.436706,0.932253,0.0219264,0.926977,0.564787,0.54919,0.919879,0.907564

In [8]:
#########################
# Test
#########################
#Add a column with cancerType to the end of the data frame
df_transposed = df_transposed.assign(CancerType='LGG')
#df_cancerType = pd.DataFrame({'CancerType': ['LUAD']})
#df_temp_list = [df_cancerType, df_transposed]
#df_transposed = pd.concat(df_temp_list)
#df_transposed = df_cancerType.join(df_transposed)
#df_transposed = pd.concat([df_cancerType, df_transposed])
#Rename the index with the filename
#df_transposed.rename(index={'Beta_value':'LUAD'},inplace=True)
df_transposed.head(5) #scroll to the end to see the new column 'CancerType'

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.895405,0.531678,0.531678,0.295116,0.864376,0.769955,0.889353,0.861963,0.855146,0.0127179,...,0.353992,0.436706,0.932253,0.0219264,0.926977,0.564787,0.54919,0.919879,0.907564,LGG

In [9]:
#########################
# Test
#########################
#Read the next file
df2 = pd.read_csv("/Users/annika/annika/high-school/cs/tgca-downloads/LGG/ff4ec000-6b4f-46a0-97be-1cd1ed488bbf/jhu-usc.edu_LGG.HumanMethylation450.3.lvl-3.TCGA-FG-6688-01A-11D-1894-05.gdc_hg38.txt", sep = "\t")
#Sort by the column which has the 'Composite Element REF'
df2.sort_values(by='Composite Element REF', inplace=True)
#Imputation by mean values to fill up missing values
df2['Beta_value'].fillna(df2['Beta_value'].mean(),inplace=True) 
#transpose the rows and columns
df2_transposed = df2.T
# Create a new variable called 'header' from the first row of the dataset
df2_headers = df2_transposed.iloc[0] 
# Replace the dataframe with a new one which does not contain the first row
df2_transposed = df2_transposed[1:2]
# Rename the dataframe's column values with the header variable
df2_transposed.rename(columns = df2_headers, inplace=True)
df2_transposed = df2_transposed.assign(CancerType='LGG')
#df2_transposed.rename(index={'Beta_value':'LUAD'},inplace=True)
df2_transposed.head()

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.678816,0.493212,0.493212,0.472224,0.91948,0.772075,0.667295,0.707024,0.184839,0.017155,...,0.324267,0.429051,0.0208661,0.512919,0.482934,0.524506,0.517839,0.459097,0.565741,LGG

In [10]:
#########################
# Test
#########################
#concat the dataframes from the 2 files
dflist2 = [df_transposed]
dflist2.append(df2_transposed)
#dflist2 = [df_transposed, df2_transposed]
dfFinal2 = pd.concat(dflist2)
dfFinal2.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.895405,0.531678,0.531678,0.295116,0.864376,0.769955,0.889353,0.861963,0.855146,0.0127179,...,0.353992,0.436706,0.932253,0.0219264,0.926977,0.564787,0.54919,0.919879,0.907564,LGG
Beta_value,0.678816,0.493212,0.493212,0.472224,0.91948,0.772075,0.667295,0.707024,0.184839,0.017155,...,0.324267,0.429051,0.0208661,0.512919,0.482934,0.524506,0.517839,0.459097,0.565741,LGG

In [11]:
#########################
# Test
#########################
# Save to csv file
filename = "LGG_betaValuesTesting2.csv"
dfFinal2.to_csv(filename,  index = False) # Do not save the index

In [12]:
#########################
# Test
#########################
#read from csv file in chunks
#filename = "LUAD_betaValuesTesting2.csv"
dfFrameList = []
for chunkTemp in pd.read_csv(filename, chunksize=1):
    dfFrameList.append(chunkTemp)
dataFrame = pd.concat(dfFrameList)        
dataFrame.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
0,0.895405,0.531678,0.531678,0.295116,0.864376,0.769955,0.889353,0.861963,0.855146,0.012718,...,0.353992,0.436706,0.932253,0.021926,0.926977,0.564787,0.549190,0.919879,0.907564,LGG
1,0.678816,0.493212,0.493212,0.472224,0.919480,0.772075,0.667295,0.707024,0.184839,0.017155,...,0.324267,0.429051,0.020866,0.512919,0.482934,0.524506,0.517839,0.459097,0.565741,LGG

In [13]:
#########################
# Program to preprocess all raw files for a cancer type
#########################
import pandas as pd
import os
import glob # Use glob to read files with wildcards

# Location for LUAD files
#For all files use this path
path = "/Users/annika/annika/high-school/cs/tgca-downloads/LGG/*/*n450*.*txt"

# Get the list of files
dirList = glob.glob(path)
# Initialize a list
dflist = []
for d in dirList:
    # Read the next file
    df3 = pd.read_csv(d, sep = "\t")
    # Sort by the column which has the 'Composite Element REF' so that 
    # the methalyation sites are sorted
    df3.sort_values(by='Composite Element REF', inplace=True)
    # Imputation by mean values to fill up missing values
    df3['Beta_value'].fillna(df3['Beta_value'].mean(),inplace=True) 
    # Transpose the rows and columns, so that all beta values are in a row
    df3_transposed = df3.T
    # Create a new variable called 'header' from the first row of the dataset which are
    # the values of 'Composite Element REF' e.g. cg00000029
    df3_headers = df3_transposed.iloc[0] 
    # Replace the dataframe with a new one which only contains the beta values
    df3_transposed = df3_transposed[1:2]
    # Rename the dataframe's column names with the header variable i.e. 
    # 'Composite Element REF' e.g. cg00000029
    df3_transposed.rename(columns = df3_headers, inplace=True)
    # Create a new column with the column name as 'CancerType' and value as 'LUAD'
    df3_transposed = df3_transposed.assign(CancerType='LGG')
    # concat the dataframes into a list
    dflist.append(df3_transposed)
# Convert the list to a dataframe    
dfFinal = pd.concat(dflist)
# Save the dataframe to csv file, do not save the index
dfFinal.to_csv("../../data/LGG/LGG_betaValuesOnly.csv", index = False) 
# Now the raw files can be deleted and only the csv files can be retained.

In [3]:
#dfFinal.to_csv("../../data/LUAD/LUAD_betaValuesOnly.csv", index = False) 
# Now the raw files can be deleted and only the csv files can be retained.

In [14]:
#########################
# Test
#########################
dfFinal.head(10)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.534983,0.472411,0.472411,0.161828,0.872788,0.548175,0.706446,0.58579,0.281631,0.0167505,...,0.372023,0.522942,0.570714,0.0438854,0.928532,0.501821,0.039186,0.0486613,0.680673,LGG
Beta_value,0.70875,0.474028,0.474028,0.45218,0.896702,0.618546,0.646753,0.686015,0.255726,0.0130715,...,0.969554,0.491915,0.501871,0.519895,0.0451603,0.0219115,0.531013,0.47347,0.934466,LGG
Beta_value,0.859662,0.540263,0.540263,0.220541,0.887298,0.687891,0.880254,0.887049,0.87317,0.0128061,...,0.322704,0.303635,0.96843,0.477115,0.931226,0.96063,0.0404749,0.038867,0.914334,LGG
Beta_value,0.882891,0.535704,0.535704,0.752095,0.891607,0.705398,0.852721,0.784037,0.799774,0.0167298,...,0.0134692,0.423065,0.809013,0.0224759,0.94795,0.522859,0.063981,0.4893,0.933675,LGG
Beta_value,0.89972,0.532888,0.532888,0.103877,0.918446,0.685092,0.662629,0.538768,0.823672,0.0101353,...,0.15691,0.926019,0.503562,0.97277,0.0627048,0.969672,0.964845,0.0375711,0.925991,LGG
Beta_value,0.849017,0.537174,0.537174,0.107498,0.91146,0.836766,0.829744,0.816272,0.809011,0.0120733,...,0.971174,0.477998,0.97082,0.522697,0.952064,0.970332,0.963122,0.497215,0.678562,LGG
Beta_value,0.308913,0.452589,0.452589,0.211689,0.910916,0.550243,0.307405,0.74956,0.161287,0.0116111,...,0.425173,0.0583399,0.0213901,0.52517,0.393441,0.0292361,0.958868,0.039449,0.953791,LGG
Beta_value,0.911105,0.564139,0.564139,0.108415,0.878222,0.706167,0.93732,0.901046,0.892201,0.0157415,...,0.363685,0.896784,0.505491,0.0248314,0.0417506,0.0287458,0.952953,0.496402,0.926359,LGG
Beta_value,0.659795,0.558286,0.558286,0.721882,0.936123,0.691066,0.907657,0.766033,0.754606,0.0135554,...,0.0143059,0.0396074,0.392485,0.0456327,0.0357148,0.0280017,0.0391191,0.400031,0.569509,LGG
Beta_value,0.555033,0.543463,0.543463,0.633019,0.92241,0.672027,0.884944,0.761721,0.797072,0.0160781,...,0.0163474,0.260613,0.967048,0.482879,0.950074,0.966188,0.51378,0.937037,0.949143,LGG

In [4]:
dfFinal.shape

(202, 485578)

In [10]:
#########################
# Test
#########################
#Save to csv file
# dfFinal.to_csv("LUAD_betaValuesOnly.csv",  index = False)
#dfFinal.to_csv("LUAD_betaValuesOnly.csv")