In [1]:
import pandas as pd
import os

In [2]:
#########################
# Test
#########################
df = pd.read_csv("/Users/annika/annika/high-school/cs/tgca-downloads/LAML/feddb7a5-aa15-4c70-a989-d8472cce7bb3/jhu-usc.edu_LAML.HumanMethylation450.2.lvl-3.TCGA-AB-2950-03A-01D-0742-05.gdc_hg38.txt", sep = "\t")
df.sort_values(by='Composite Element REF', inplace=True)
df.head(5)

,Composite Element REF,Beta_value,Chromosome,Start,End,Gene_Symbol,Gene_Type,Transcript_ID,Position_to_TSS,CGI_Coordinate,Feature_Type
0,cg00000029,0.138993,chr16,53434200,53434201,RBL2;RBL2;RBL2,protein_coding;protein_coding;protein_coding,ENST00000262133.9;ENST00000544405.5;ENST000005...,-221;-1420;222,CGI:chr16:53434489-53435297,N_Shore
1,cg00000108,NaN,chr3,37417715,37417716,C3orf35;C3orf35;C3orf35;C3orf35;C3orf35;C3orf3...,lincRNA;lincRNA;lincRNA;lincRNA;lincRNA;lincRN...,ENST00000328376.8;ENST00000332506.6;ENST000004...,18552;18552;6505;31445;18143;447;18552;18552,CGI:chr3:37451927-37453047,.
2,cg00000109,NaN,chr3,172198247,172198248,FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B,protein_coding;protein_coding;protein_coding;p...,ENST00000336824.7;ENST00000415807.5;ENST000004...,157692;158618;151333;71272;158587;71273,CGI:chr3:172039703-172040934,.
3,cg00000165,0.189438,chr1,90729117,90729118,.,.,.,.,CGI:chr1:90724932-90727247,S_Shore
4,cg00000236,0.656464,chr8,42405776,42405777,VDAC3,protein_coding,ENST00000022615.7,13872,CGI:chr8:42410918-42411241,.

In [3]:
#########################
# Test
#########################
#Imputation by mean values to fill up missing values
df['Beta_value'].fillna(df['Beta_value'].mean(),inplace=True) 
df.head(5)

,Composite Element REF,Beta_value,Chromosome,Start,End,Gene_Symbol,Gene_Type,Transcript_ID,Position_to_TSS,CGI_Coordinate,Feature_Type
0,cg00000029,0.138993,chr16,53434200,53434201,RBL2;RBL2;RBL2,protein_coding;protein_coding;protein_coding,ENST00000262133.9;ENST00000544405.5;ENST000005...,-221;-1420;222,CGI:chr16:53434489-53435297,N_Shore
1,cg00000108,0.478241,chr3,37417715,37417716,C3orf35;C3orf35;C3orf35;C3orf35;C3orf35;C3orf3...,lincRNA;lincRNA;lincRNA;lincRNA;lincRNA;lincRN...,ENST00000328376.8;ENST00000332506.6;ENST000004...,18552;18552;6505;31445;18143;447;18552;18552,CGI:chr3:37451927-37453047,.
2,cg00000109,0.478241,chr3,172198247,172198248,FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B,protein_coding;protein_coding;protein_coding;p...,ENST00000336824.7;ENST00000415807.5;ENST000004...,157692;158618;151333;71272;158587;71273,CGI:chr3:172039703-172040934,.
3,cg00000165,0.189438,chr1,90729117,90729118,.,.,.,.,CGI:chr1:90724932-90727247,S_Shore
4,cg00000236,0.656464,chr8,42405776,42405777,VDAC3,protein_coding,ENST00000022615.7,13872,CGI:chr8:42410918-42411241,.

In [4]:
#########################
# Test
#########################
#transpose the rows and columns
df_transposed = df.T
df_transposed.head(5)

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
Beta_value,0.138993,0.478241,0.478241,0.189438,0.656464,0.739008,0.583307,0.812989,0.198219,0.017452,...,0.964722,0.0150389,0.458428,0.542536,0.961926,0.543292,0.972063,0.525792,0.601692,0.947252
Chromosome,chr16,chr3,chr3,chr1,chr8,chr14,chr16,chr8,chr1,chr15,...,chr6,chrX,chr21,chr1,chr5,chr6,chr3,chr15,chr2,chr3
Start,53434200,37417715,172198247,90729117,42405776,68874422,28878779,41310283,230425047,22838620,...,47163083,15867308,32625974,11429621,35000207,67522149,14617359,45707625,12008094,86613005
End,53434201,37417716,172198248,90729118,42405777,68874423,28878780,41310284,230425048,22838621,...,47163083,15867308,32625974,11429621,35000207,67522149,14617359,45707625,12008094,86613005

In [5]:
#########################
# Test
#########################
# Create a new variable called 'header' from the first row of the dataset
df_headers = df_transposed.iloc[0] 
df_headers.head(5)

0    cg00000029
1    cg00000108
2    cg00000109
3    cg00000165
4    cg00000236
Name: Composite Element REF, dtype: object

In [6]:
#########################
# Test
#########################
# Replace the dataframe with a new one which does not contain the first row
df_transposed = df_transposed[1:2]
df_transposed.head(5)

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
Beta_value,0.138993,0.478241,0.478241,0.189438,0.656464,0.739008,0.583307,0.812989,0.198219,0.017452,...,0.964722,0.0150389,0.458428,0.542536,0.961926,0.543292,0.972063,0.525792,0.601692,0.947252

In [7]:
#########################
# Test
#########################
# Rename the dataframe's column values with the header variable
df_transposed.rename(columns = df_headers, inplace=True)
df_transposed.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
Beta_value,0.138993,0.478241,0.478241,0.189438,0.656464,0.739008,0.583307,0.812989,0.198219,0.017452,...,0.964722,0.0150389,0.458428,0.542536,0.961926,0.543292,0.972063,0.525792,0.601692,0.947252

In [8]:
#########################
# Test
#########################
#Add a column with cancerType to the end of the data frame
df_transposed = df_transposed.assign(CancerType='LAML')
df_transposed.head(5) #scroll to the end to see the new column 'CancerType'

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.138993,0.478241,0.478241,0.189438,0.656464,0.739008,0.583307,0.812989,0.198219,0.017452,...,0.0150389,0.458428,0.542536,0.961926,0.543292,0.972063,0.525792,0.601692,0.947252,LAML

In [9]:
#########################
# Test
#########################
#Read the next file
df2 = pd.read_csv("/Users/annika/annika/high-school/cs/tgca-downloads/LAML/fb3cefc1-15d1-4419-82b0-9c0ebe6dff55/jhu-usc.edu_LAML.HumanMethylation450.2.lvl-3.TCGA-AB-3009-03A-01D-0741-05.gdc_hg38.txt", sep = "\t")
#Sort by the column which has the 'Composite Element REF'
df2.sort_values(by='Composite Element REF', inplace=True)
#Imputation by mean values to fill up missing values
df2['Beta_value'].fillna(df2['Beta_value'].mean(),inplace=True) 
#transpose the rows and columns
df2_transposed = df2.T
# Create a new variable called 'header' from the first row of the dataset
df2_headers = df2_transposed.iloc[0] 
# Replace the dataframe with a new one which does not contain the first row
df2_transposed = df2_transposed[1:2]
# Rename the dataframe's column values with the header variable
df2_transposed.rename(columns = df2_headers, inplace=True)
df2_transposed = df2_transposed.assign(CancerType='LAML')
df2_transposed.head()

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.348211,0.607842,0.607842,0.94179,0.950726,0.806214,0.822795,0.789281,0.864066,0.00970401,...,0.0151585,0.455613,0.0154272,0.497342,0.0270167,0.0200141,0.533033,0.550427,0.958751,LAML

In [10]:
#########################
# Test
#########################
#concat the dataframes from the 2 files
dflist2 = [df_transposed]
dflist2.append(df2_transposed)
dfFinal2 = pd.concat(dflist2)
dfFinal2.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.138993,0.478241,0.478241,0.189438,0.656464,0.739008,0.583307,0.812989,0.198219,0.017452,...,0.0150389,0.458428,0.542536,0.961926,0.543292,0.972063,0.525792,0.601692,0.947252,LAML
Beta_value,0.348211,0.607842,0.607842,0.94179,0.950726,0.806214,0.822795,0.789281,0.864066,0.00970401,...,0.0151585,0.455613,0.0154272,0.497342,0.0270167,0.0200141,0.533033,0.550427,0.958751,LAML

In [11]:
#########################
# Test
#########################
# Save to csv file
filename = "LAML_betaValuesTesting2.csv"
dfFinal2.to_csv(filename,  index = False) # Do not save the index

In [12]:
#########################
# Test
#########################
#read from csv file in chunks
#filename = "LUAD_betaValuesTesting2.csv"
dfFrameList = []
for chunkTemp in pd.read_csv(filename, chunksize=1):
    dfFrameList.append(chunkTemp)
dataFrame = pd.concat(dfFrameList)        
dataFrame.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
0,0.138993,0.478241,0.478241,0.189438,0.656464,0.739008,0.583307,0.812989,0.198219,0.017452,...,0.015039,0.458428,0.542536,0.961926,0.543292,0.972063,0.525792,0.601692,0.947252,LAML
1,0.348211,0.607842,0.607842,0.941790,0.950726,0.806214,0.822795,0.789281,0.864066,0.009704,...,0.015159,0.455613,0.015427,0.497342,0.027017,0.020014,0.533033,0.550427,0.958751,LAML

In [13]:
#########################
# Program to preprocess all raw files for a cancer type
#########################
import pandas as pd
import os
import glob # Use glob to read files with wildcards

# Location for LUAD files
#For all files use this path
path = "/Users/annika/annika/high-school/cs/tgca-downloads/LAML/*/*n450*.*txt"

# Get the list of files
dirList = glob.glob(path)
# Initialize a list
dflist = []
for d in dirList:
    # Read the next file
    df3 = pd.read_csv(d, sep = "\t")
    # Sort by the column which has the 'Composite Element REF' so that 
    # the methalyation sites are sorted
    df3.sort_values(by='Composite Element REF', inplace=True)
    # Imputation by mean values to fill up missing values
    df3['Beta_value'].fillna(df3['Beta_value'].mean(),inplace=True) 
    # Transpose the rows and columns, so that all beta values are in a row
    df3_transposed = df3.T
    # Create a new variable called 'header' from the first row of the dataset which are
    # the values of 'Composite Element REF' e.g. cg00000029
    df3_headers = df3_transposed.iloc[0] 
    # Replace the dataframe with a new one which only contains the beta values
    df3_transposed = df3_transposed[1:2]
    # Rename the dataframe's column names with the header variable i.e. 
    # 'Composite Element REF' e.g. cg00000029
    df3_transposed.rename(columns = df3_headers, inplace=True)
    # Create a new column with the column name as 'CancerType' and value as 'LUAD'
    df3_transposed = df3_transposed.assign(CancerType='LAML')
    # concat the dataframes into a list
    dflist.append(df3_transposed)
# Convert the list to a dataframe    
dfFinal = pd.concat(dflist)
# Save the dataframe to csv file, do not save the index
dfFinal.to_csv("../../data/LAML/LAML_betaValuesOnly.csv", index = False) 
# Now the raw files can be deleted and only the csv files can be retained.

In [3]:
#dfFinal.to_csv("../../data/LUAD/LUAD_betaValuesOnly.csv", index = False) 
# Now the raw files can be deleted and only the csv files can be retained.

In [14]:
#########################
# Test
#########################
dfFinal.head(10)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.500862,0.482156,0.482156,0.100217,0.629356,0.772976,0.713143,0.57515,0.537398,0.0122801,...,0.0157135,0.449765,0.524101,0.963251,0.556909,0.536838,0.969723,0.944524,0.959916,LAML
Beta_value,0.448804,0.469995,0.469995,0.116164,0.628281,0.817711,0.699473,0.576168,0.560563,0.011206,...,0.392611,0.434138,0.0139357,0.502346,0.973326,0.022438,0.539603,0.513327,0.966936,LAML
Beta_value,0.620366,0.498182,0.498182,0.584296,0.913059,0.739498,0.888225,0.178873,0.528879,0.0127537,...,0.972767,0.478342,0.0238783,0.503633,0.0449367,0.0385981,0.508438,0.0622682,0.940969,LAML
Beta_value,0.499826,0.515442,0.515442,0.70966,0.820705,0.821612,0.816033,0.529931,0.55442,0.0136188,...,0.979987,0.961326,0.982646,0.977336,0.0203555,0.978508,0.97713,0.946196,0.619466,LAML
Beta_value,0.129281,0.49375,0.49375,0.672165,0.829428,0.837624,0.796367,0.217483,0.487194,0.010908,...,0.3891,0.432861,0.972949,0.499549,0.960712,0.021743,0.968846,0.0374993,0.954054,LAML
Beta_value,0.813092,0.51656,0.51656,0.164544,0.882415,0.723941,0.812573,0.523647,0.721416,0.0108512,...,0.0148904,0.500306,0.97262,0.9679,0.955098,0.578887,0.507436,0.59206,0.69303,LAML
Beta_value,0.626692,0.496209,0.496209,0.11618,0.778235,0.761027,0.771679,0.82816,0.501514,0.0126254,...,0.0177316,0.0397613,0.535675,0.504878,0.555815,0.545876,0.034731,0.923463,0.938398,LAML
Beta_value,0.693413,0.505621,0.505621,0.404484,0.887235,0.834124,0.870578,0.615553,0.559818,0.0109001,...,0.412875,0.484383,0.399087,0.49396,0.96258,0.975365,0.0363896,0.0362731,0.958548,LAML
Beta_value,0.231984,0.518863,0.518863,0.551796,0.83841,0.86374,0.848999,0.485979,0.132753,0.0125757,...,0.975169,0.450044,0.0155219,0.0177508,0.518303,0.977514,0.533631,0.498589,0.588487,LAML
Beta_value,0.513772,0.493209,0.493209,0.831873,0.648432,0.847047,0.7829,0.622522,0.189929,0.0138055,...,0.472564,0.458889,0.548667,0.50589,0.0263127,0.542004,0.0346243,0.954536,0.962859,LAML

In [15]:
dfFinal.shape

(201, 485578)