In [19]:
import pandas as pd
import os
#import fnmatch

In [80]:
#########################
# Test
#########################
df = pd.read_csv("/Users/annika/annika/high-school/cs/tgca-downloads/LUAD/ff9ab81e-4b88-4aca-9623-3747bbb14b83/jhu-usc.edu_LUSC.HumanMethylation450.18.lvl-3.TCGA-6A-AB49-01A-12D-A408-05.gdc_hg38.txt", sep = "\t")
df.sort_values(by='Composite Element REF', inplace=True)
#df.dtypes; #get the types
#type(df); #find the type of the variable
df.head(5)

,Composite Element REF,Beta_value,Chromosome,Start,End,Gene_Symbol,Gene_Type,Transcript_ID,Position_to_TSS,CGI_Coordinate,Feature_Type
0,cg00000029,0.174980,chr16,53434200,53434201,RBL2;RBL2;RBL2,protein_coding;protein_coding;protein_coding,ENST00000262133.9;ENST00000544405.5;ENST000005...,-221;-1420;222,CGI:chr16:53434489-53435297,N_Shore
1,cg00000108,NaN,chr3,37417715,37417716,C3orf35;C3orf35;C3orf35;C3orf35;C3orf35;C3orf3...,lincRNA;lincRNA;lincRNA;lincRNA;lincRNA;lincRN...,ENST00000328376.8;ENST00000332506.6;ENST000004...,18552;18552;6505;31445;18143;447;18552;18552,CGI:chr3:37451927-37453047,.
2,cg00000109,NaN,chr3,172198247,172198248,FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B,protein_coding;protein_coding;protein_coding;p...,ENST00000336824.7;ENST00000415807.5;ENST000004...,157692;158618;151333;71272;158587;71273,CGI:chr3:172039703-172040934,.
3,cg00000165,0.593060,chr1,90729117,90729118,.,.,.,.,CGI:chr1:90724932-90727247,S_Shore
4,cg00000236,0.898874,chr8,42405776,42405777,VDAC3,protein_coding,ENST00000022615.7,13872,CGI:chr8:42410918-42411241,.

In [81]:
#########################
# Test
#########################
#Imputation by mean values to fill up missing values
df['Beta_value'].fillna(df['Beta_value'].mean(),inplace=True) 
df.head(5)

,Composite Element REF,Beta_value,Chromosome,Start,End,Gene_Symbol,Gene_Type,Transcript_ID,Position_to_TSS,CGI_Coordinate,Feature_Type
0,cg00000029,0.174980,chr16,53434200,53434201,RBL2;RBL2;RBL2,protein_coding;protein_coding;protein_coding,ENST00000262133.9;ENST00000544405.5;ENST000005...,-221;-1420;222,CGI:chr16:53434489-53435297,N_Shore
1,cg00000108,0.430431,chr3,37417715,37417716,C3orf35;C3orf35;C3orf35;C3orf35;C3orf35;C3orf3...,lincRNA;lincRNA;lincRNA;lincRNA;lincRNA;lincRN...,ENST00000328376.8;ENST00000332506.6;ENST000004...,18552;18552;6505;31445;18143;447;18552;18552,CGI:chr3:37451927-37453047,.
2,cg00000109,0.430431,chr3,172198247,172198248,FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B;FNDC3B,protein_coding;protein_coding;protein_coding;p...,ENST00000336824.7;ENST00000415807.5;ENST000004...,157692;158618;151333;71272;158587;71273,CGI:chr3:172039703-172040934,.
3,cg00000165,0.593060,chr1,90729117,90729118,.,.,.,.,CGI:chr1:90724932-90727247,S_Shore
4,cg00000236,0.898874,chr8,42405776,42405777,VDAC3,protein_coding,ENST00000022615.7,13872,CGI:chr8:42410918-42411241,.

In [82]:
#########################
# Test
#########################
#transpose the rows and columns
df_transposed = df.T
df_transposed.head(5)

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
Composite Element REF,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
Beta_value,0.17498,0.430431,0.430431,0.59306,0.898874,0.384079,0.602559,0.754391,0.12034,0.0125914,...,0.968323,0.0141474,0.0697833,0.178144,0.974763,0.0915756,0.956101,0.62743,0.684369,0.098075
Chromosome,chr16,chr3,chr3,chr1,chr8,chr14,chr16,chr8,chr1,chr15,...,chr6,chrX,chr21,chr1,chr5,chr6,chr3,chr15,chr2,chr3
Start,53434200,37417715,172198247,90729117,42405776,68874422,28878779,41310283,230425047,22838620,...,47163083,15867308,32625974,11429621,35000207,67522149,14617359,45707625,12008094,86613005
End,53434201,37417716,172198248,90729118,42405777,68874423,28878780,41310284,230425048,22838621,...,47163083,15867308,32625974,11429621,35000207,67522149,14617359,45707625,12008094,86613005

In [83]:
#########################
# Test
#########################
# Create a new variable called 'header' from the first row of the dataset
df_headers = df_transposed.iloc[0] 
#type(df_headers)
df_headers.head(5)

0    cg00000029
1    cg00000108
2    cg00000109
3    cg00000165
4    cg00000236
Name: Composite Element REF, dtype: object

In [84]:
#########################
# Test
#########################
# Replace the dataframe with a new one which does not contain the first row
df_transposed = df_transposed[1:2]
df_transposed.head(5)

,0,1,2,3,4,5,6,7,8,9,...,485567,485568,485569,485570,485571,485572,485573,485574,485575,485576
Beta_value,0.17498,0.430431,0.430431,0.59306,0.898874,0.384079,0.602559,0.754391,0.12034,0.0125914,...,0.968323,0.0141474,0.0697833,0.178144,0.974763,0.0915756,0.956101,0.62743,0.684369,0.098075

In [85]:
#########################
# Test
#########################
# Rename the dataframe's column values with the header variable
df_transposed.rename(columns = df_headers, inplace=True)
df_transposed.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs7746156,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873
Beta_value,0.17498,0.430431,0.430431,0.59306,0.898874,0.384079,0.602559,0.754391,0.12034,0.0125914,...,0.968323,0.0141474,0.0697833,0.178144,0.974763,0.0915756,0.956101,0.62743,0.684369,0.098075

In [86]:
#########################
# Test
#########################
#Add a column with cancerType to the end of the data frame
df_transposed = df_transposed.assign(CancerType='LUAD')
#df_cancerType = pd.DataFrame({'CancerType': ['LUAD']})
#df_temp_list = [df_cancerType, df_transposed]
#df_transposed = pd.concat(df_temp_list)
#df_transposed = df_cancerType.join(df_transposed)
#df_transposed = pd.concat([df_cancerType, df_transposed])
#Rename the index with the filename
#df_transposed.rename(index={'Beta_value':'LUAD'},inplace=True)
df_transposed.head(5) #scroll to the end to see the new column 'CancerType'

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.17498,0.430431,0.430431,0.59306,0.898874,0.384079,0.602559,0.754391,0.12034,0.0125914,...,0.0141474,0.0697833,0.178144,0.974763,0.0915756,0.956101,0.62743,0.684369,0.098075,LUAD

In [77]:
#########################
# Test
#########################
#Read the next file
df2 = pd.read_csv("/Users/annika/annika/high-school/cs/tgca-downloads/LUAD/f9ed699b-118b-4499-a0e2-daa94c413157/jhu-usc.edu_LUAD.HumanMethylation450.4.lvl-3.TCGA-05-4427-01A-21D-1856-05.gdc_hg38.txt", sep = "\t")
#Sort by the column which has the 'Composite Element REF'
df2.sort_values(by='Composite Element REF', inplace=True)
#Imputation by mean values to fill up missing values
df2['Beta_value'].fillna(df2['Beta_value'].mean(),inplace=True) 
#transpose the rows and columns
df2_transposed = df2.T
# Create a new variable called 'header' from the first row of the dataset
df2_headers = df2_transposed.iloc[0] 
# Replace the dataframe with a new one which does not contain the first row
df2_transposed = df2_transposed[1:2]
# Rename the dataframe's column values with the header variable
df2_transposed.rename(columns = df2_headers, inplace=True)
df2_transposed = df2_transposed.assign(CancerType='LUAD')
#df2_transposed.rename(index={'Beta_value':'LUAD'},inplace=True)
df2_transposed.head();

In [87]:
#########################
# Test
#########################
#concat the dataframes from the 2 files
dflist2 = [df_transposed]
dflist2.append(df2_transposed)
#dflist2 = [df_transposed, df2_transposed]
dfFinal2 = pd.concat(dflist2)
dfFinal2.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.17498,0.430431,0.430431,0.59306,0.898874,0.384079,0.602559,0.754391,0.12034,0.0125914,...,0.0141474,0.0697833,0.178144,0.974763,0.0915756,0.956101,0.62743,0.684369,0.098075,LUAD
Beta_value,0.27439,0.431848,0.431848,0.553264,0.873772,0.645023,0.730501,0.365551,0.535513,0.0254682,...,0.361748,0.762181,0.927842,0.937726,0.0672241,0.556976,0.485983,0.0537872,0.590733,LUAD

In [ ]:
#########################
# Test
#########################
# Save to csv file
filename = "LUAD_betaValuesTesting2.csv"
dfFinal2.to_csv(filename,  index = False) # Do not save the index

In [79]:
#########################
# Test
#########################
#read from csv file in chunks
#filename = "LUAD_betaValuesTesting2.csv"
dfFrameList = []
for chunkTemp in pd.read_csv(filename, chunksize=1):
    dfFrameList.append(chunkTemp)
dataFrame = pd.concat(dfFrameList)        
dataFrame.head(5)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
0,0.17498,0.430431,0.430431,0.593060,0.898874,0.384079,0.602559,0.754391,0.120340,0.012591,...,0.014147,0.069783,0.178144,0.974763,0.091576,0.956101,0.627430,0.684369,0.098075,LUAD
1,0.27439,0.431848,0.431848,0.553264,0.873772,0.645023,0.730501,0.365551,0.535513,0.025468,...,0.361748,0.762181,0.927842,0.937726,0.067224,0.556976,0.485983,0.053787,0.590733,LUAD

In [1]:
#########################
# Program to preprocess all raw files for a cancer type
#########################
import pandas as pd
import os
import glob # Use glob to read files with wildcards

# Location for LUAD files
#For all files use this path
#path = "/Users/annika/annika/high-school/cs/tgca-downloads/*/*n450*txt"
#For about 202 files use this path
path = "/Users/annika/annika/high-school/cs/tgca-downloads/LUAD/*/*n450.1*.*txt"

# Get the list of files
dirList = glob.glob(path)
# Initialize a list
dflist = []
for d in dirList:
    # Read the next file
    df3 = pd.read_csv(d, sep = "\t")
    # Sort by the column which has the 'Composite Element REF' so that 
    # the methalyation sites are sorted
    df3.sort_values(by='Composite Element REF', inplace=True)
    # Imputation by mean values to fill up missing values
    df3['Beta_value'].fillna(df3['Beta_value'].mean(),inplace=True) 
    # Transpose the rows and columns, so that all beta values are in a row
    df3_transposed = df3.T
    # Create a new variable called 'header' from the first row of the dataset which are
    # the values of 'Composite Element REF' e.g. cg00000029
    df3_headers = df3_transposed.iloc[0] 
    # Replace the dataframe with a new one which only contains the beta values
    df3_transposed = df3_transposed[1:2]
    # Rename the dataframe's column names with the header variable i.e. 
    # 'Composite Element REF' e.g. cg00000029
    df3_transposed.rename(columns = df3_headers, inplace=True)
    # Create a new column with the column name as 'CancerType' and value as 'LUAD'
    df3_transposed = df3_transposed.assign(CancerType='LUAD')
    # concat the dataframes into a list
    dflist.append(df3_transposed)
# Convert the list to a dataframe    
dfFinal = pd.concat(dflist)
# Save the dataframe to csv file, do not save the index
dfFinal.to_csv("../../data/LUAD/LUAD_betaValuesOnly.csv", index = False) 
# Now the raw files can be deleted and only the csv files can be retained.

FileNotFoundError: [Errno 2] No such file or directory: '../data/LUAD/LUAD_betaValuesOnly.csv'

In [3]:
#dfFinal.to_csv("../../data/LUAD/LUAD_betaValuesOnly.csv", index = False) 
# Now the raw files can be deleted and only the csv files can be retained.

In [2]:
#########################
# Test
#########################
dfFinal.head(10)

,cg00000029,cg00000108,cg00000109,cg00000165,cg00000236,cg00000289,cg00000292,cg00000321,cg00000363,cg00000622,...,rs798149,rs845016,rs877309,rs9292570,rs9363764,rs939290,rs951295,rs966367,rs9839873,CancerType
Beta_value,0.249354,0.518107,0.518107,0.513046,0.853204,0.705116,0.794352,0.649071,0.431573,0.0190149,...,0.402819,0.413653,0.0316411,0.939549,0.0776958,0.333082,0.0645438,0.475144,0.893121,LUAD
Beta_value,0.159052,0.417547,0.417547,0.198068,0.86308,0.5936,0.422997,0.447784,0.180894,0.022709,...,0.964118,0.95612,0.526658,0.177363,0.0523126,0.285201,0.946629,0.928094,0.783367,LUAD
Beta_value,0.276347,0.47094,0.47094,0.563651,0.881473,0.697009,0.510482,0.510299,0.186251,0.0165168,...,0.968551,0.898843,0.701324,0.495003,0.937278,0.0261091,0.0527379,0.499191,0.854084,LUAD
Beta_value,0.139515,0.47205,0.47205,0.378171,0.866939,0.701795,0.682175,0.429718,0.189245,0.0193159,...,0.0237197,0.941081,0.0346527,0.951808,0.928918,0.0400636,0.0828942,0.502434,0.889536,LUAD
Beta_value,0.212803,0.420617,0.420617,0.677257,0.757211,0.408809,0.490813,0.542868,0.185063,0.0240568,...,0.939187,0.103774,0.0336561,0.0495039,0.0876505,0.864022,0.572588,0.879559,0.570101,LUAD
Beta_value,0.0805703,0.454083,0.454083,0.811211,0.914021,0.691389,0.693017,0.55993,0.121024,0.0157872,...,0.0116869,0.455904,0.210787,0.457451,0.946673,0.206325,0.528883,0.0256103,0.923401,LUAD
Beta_value,0.307506,0.446609,0.446609,0.201405,0.803819,0.390484,0.632353,0.339145,0.26796,0.0233158,...,0.925746,0.0764683,0.515004,0.945583,0.092043,0.54729,0.0639795,0.823624,0.0976305,LUAD
Beta_value,0.477089,0.472587,0.472587,0.329425,0.840038,0.656121,0.646473,0.438823,0.366391,0.0185972,...,0.421055,0.454943,0.947157,0.945934,0.910979,0.0401037,0.530902,0.927295,0.65444,LUAD
Beta_value,0.0888716,0.429825,0.429825,0.732556,0.90897,0.702688,0.431884,0.401019,0.203726,0.0143619,...,0.970322,0.203457,0.971423,0.393583,0.533958,0.790356,0.428577,0.92544,0.939447,LUAD
Beta_value,0.170802,0.492869,0.492869,0.471985,0.841084,0.593019,0.570765,0.465042,0.404086,0.0212766,...,0.0226877,0.0475757,0.018783,0.492372,0.417806,0.534404,0.940411,0.934697,0.0883675,LUAD

In [4]:
dfFinal.shape

(202, 485578)

In [10]:
#########################
# Test
#########################
#Save to csv file
# dfFinal.to_csv("LUAD_betaValuesOnly.csv",  index = False)
#dfFinal.to_csv("LUAD_betaValuesOnly.csv")